import type { ConfigRecipeName } from "./config-recipes.js"
import type { McpToolName } from "./observability-catalog.js"
import type { SetupPresetName } from "./setup-presets.js"

export const MIGRATION_SOURCE_IDS = Object.freeze([
  "cappyeo@0.26.0",
  "hypark@0.1.1",
  "jaimen-bell@0.1.1",
  "oratorian@1.1.4",
  "pasympa@2.2.0",
  "targeted-reader@1.0.0",
] as const)

export type MigrationSourceId = typeof MIGRATION_SOURCE_IDS[number]
export type MigrationAuditFidelity = "tagged-source" | "version-matched-public-source"
export type MigrationDisposition = "intentionally-excluded" | "review-required" | "supported"

export interface MigrationGroupDefinition {
  readonly disposition: MigrationDisposition
  readonly id: string
  readonly instruction: string
  readonly outcome: string
  readonly recipes: readonly ConfigRecipeName[]
  readonly sourceNames?: readonly string[]
  readonly sourcePrefixes?: readonly string[]
  readonly targetTools: readonly McpToolName[]
  readonly trustChange: string
}

export interface MigrationSourceDefinition {
  readonly auditFidelity: MigrationAuditFidelity
  readonly auditedInventoryDigest: `sha256:${string}`
  readonly baselinePreset: SetupPresetName
  readonly evidenceUrl: string
  readonly groups: readonly MigrationGroupDefinition[]
  readonly id: MigrationSourceId
  readonly limitations: readonly string[]
  readonly product: string
  readonly registryName: string
  readonly registryUrl: string
  readonly sourceTools: readonly string[]
  readonly version: string
}

const CAPPYEO_TOOLS = Object.freeze([
  "app_emojis_create",
  "app_emojis_delete",
  "app_emojis_get",
  "app_emojis_list",
  "app_emojis_modify",
  "application_get_activity_instance",
  "application_get_current",
  "application_get_role_connection_metadata",
  "application_modify_current",
  "application_modify_role_connection_metadata",
  "audit_log_get",
  "automod_create_rule",
  "automod_delete_rule",
  "automod_get_rule",
  "automod_list_rules",
  "automod_modify_rule",
  "channels_create_guild_channel",
  "channels_delete",
  "channels_delete_permissions",
  "channels_follow_announcement",
  "channels_forum_create_thread",
  "channels_get",
  "channels_list",
  "channels_list_active_threads_guild",
  "channels_list_joined_private_archived_threads",
  "channels_list_private_archived_threads",
  "channels_list_public_archived_threads",
  "channels_modify",
  "channels_modify_permissions",
  "channels_trigger_typing",
  "commands_bulk_overwrite_global",
  "commands_bulk_overwrite_guild",
  "commands_create_global",
  "commands_create_guild",
  "commands_delete_global",
  "commands_delete_guild",
  "commands_edit_command_permissions",
  "commands_get_command_permissions",
  "commands_get_global",
  "commands_get_guild",
  "commands_get_guild_command_permissions",
  "commands_list_global",
  "commands_list_guild",
  "commands_modify_global",
  "commands_modify_guild",
  "components_v2_build_container",
  "components_v2_build_media_gallery",
  "components_v2_build_section",
  "components_v2_edit",
  "components_v2_preview",
  "components_v2_send",
  "components_v2_send_from_template",
  "components_v2_validate",
  "discord_intent_plan",
  "emojis_create",
  "emojis_delete",
  "emojis_get",
  "emojis_list_guild",
  "emojis_modify",
  "entitlements_consume",
  "entitlements_create_test",
  "entitlements_delete_test",
  "entitlements_get",
  "entitlements_list",
  "events_create",
  "events_delete",
  "events_get",
  "events_list",
  "events_list_users",
  "events_modify",
  "guild_begin_prune",
  "guild_blueprint_apply",
  "guild_blueprint_compile",
  "guild_blueprint_evidence",
  "guild_blueprint_plan",
  "guild_delete_integration",
  "guild_get",
  "guild_get_prune_count",
  "guild_get_vanity_url",
  "guild_get_welcome_screen",
  "guild_get_widget",
  "guild_get_widget_image_url",
  "guild_get_widget_settings",
  "guild_list_integrations",
  "guild_list_voice_regions",
  "guild_modify",
  "guild_modify_current_voice_state",
  "guild_modify_user_voice_state",
  "guild_modify_welcome_screen",
  "guild_modify_widget",
  "inspiration_emoji_gg_search",
  "intelligence_classify_messages",
  "intelligence_draft_response",
  "intelligence_extract_entities",
  "intelligence_moderate_content",
  "intelligence_summarize_channel",
  "interactions_create_followup",
  "interactions_create_response",
  "interactions_delete_followup",
  "interactions_delete_original_response",
  "interactions_edit_followup",
  "interactions_edit_original_response",
  "interactions_get_followup",
  "interactions_get_original_response",
  "invites_create_channel",
  "invites_delete",
  "invites_get",
  "invites_list_channel",
  "mcp_pipeline",
  "members_add_role",
  "members_ban",
  "members_bulk_ban",
  "members_get",
  "members_get_ban",
  "members_get_current_user",
  "members_kick",
  "members_list",
  "members_list_bans",
  "members_modify",
  "members_modify_current",
  "members_remove_role",
  "members_search",
  "members_unban",
  "messages_bulk_delete",
  "messages_create_thread",
  "messages_crosspost",
  "messages_delete",
  "messages_edit",
  "messages_get",
  "messages_list_pins",
  "messages_pin",
  "messages_read",
  "messages_search_recent",
  "messages_send",
  "messages_unpin",
  "onboarding_get",
  "onboarding_modify",
  "permissions_audit_channel",
  "permissions_explain",
  "polls_end",
  "polls_get_voters",
  "reactions_create",
  "reactions_delete_all",
  "reactions_delete_own",
  "reactions_delete_user",
  "reactions_list",
  "roles_create",
  "roles_delete",
  "roles_list",
  "roles_modify",
  "roles_modify_positions",
  "skus_list",
  "soundboard_create_guild_sound",
  "soundboard_delete_guild_sound",
  "soundboard_get_guild_sound",
  "soundboard_list_default_sounds",
  "soundboard_list_guild_sounds",
  "soundboard_modify_guild_sound",
  "soundboard_send_sound",
  "stage_instances_create",
  "stage_instances_delete",
  "stage_instances_get",
  "stage_instances_modify",
  "stickers_create_guild_sticker",
  "stickers_delete_guild_sticker",
  "stickers_get",
  "stickers_get_guild_sticker",
  "stickers_list_guild",
  "stickers_list_packs",
  "stickers_modify_guild_sticker",
  "subscriptions_get",
  "subscriptions_list",
  "templates_create",
  "templates_delete",
  "templates_diff",
  "templates_get",
  "templates_inspect",
  "templates_list",
  "templates_modify",
  "templates_recommend",
  "templates_sync",
  "threads_add_member",
  "threads_get_member",
  "threads_join",
  "threads_leave",
  "threads_list_members",
  "threads_remove_member",
  "users_create_dm",
  "users_get",
  "users_get_current",
  "users_leave_guild",
  "users_list_current_user_guilds",
  "users_modify_current",
  "voice_get_current_user_state",
  "voice_get_user_state",
  "voice_list_regions",
  "webhooks_create",
  "webhooks_delete",
  "webhooks_delete_message",
  "webhooks_delete_with_token",
  "webhooks_edit_message",
  "webhooks_execute",
  "webhooks_get",
  "webhooks_get_message",
  "webhooks_get_with_token",
  "webhooks_list_channel",
  "webhooks_list_guild",
  "webhooks_modify",
  "webhooks_modify_with_token",
])

const PASYMPA_TOOLS = Object.freeze([
  "discord_add_reaction",
  "discord_add_role",
  "discord_audit_permissions",
  "discord_ban_member",
  "discord_bulk_ban",
  "discord_bulk_delete_messages",
  "discord_clone_channel",
  "discord_copy_permissions",
  "discord_create_channel",
  "discord_create_event_invite",
  "discord_create_forum_channel",
  "discord_create_forum_post",
  "discord_create_invite",
  "discord_create_role",
  "discord_create_scheduled_event",
  "discord_create_thread",
  "discord_create_webhook",
  "discord_crosspost_message",
  "discord_delete_channel",
  "discord_delete_dm",
  "discord_delete_forum_post",
  "discord_delete_invite",
  "discord_delete_message",
  "discord_delete_role",
  "discord_delete_scheduled_event",
  "discord_delete_webhook",
  "discord_delete_webhook_message",
  "discord_edit_channel",
  "discord_edit_dm",
  "discord_edit_dm_embed",
  "discord_edit_embed",
  "discord_edit_message",
  "discord_edit_role",
  "discord_edit_scheduled_event",
  "discord_edit_webhook",
  "discord_edit_webhook_message",
  "discord_fetch_pinned_messages",
  "discord_fetch_webhook_message",
  "discord_find_channel_by_name",
  "discord_follow_announcement_channel",
  "discord_forward_message",
  "discord_get_audit_log",
  "discord_get_channel_permissions",
  "discord_get_event_subscribers",
  "discord_get_forum_channels",
  "discord_get_forum_post",
  "discord_get_forum_tags",
  "discord_get_guild_info",
  "discord_get_invite",
  "discord_get_member_info",
  "discord_get_membership_screening",
  "discord_get_message_attachments",
  "discord_get_reactions",
  "discord_get_role_members",
  "discord_get_scheduled_event",
  "discord_get_server_stats",
  "discord_kick_member",
  "discord_list_bans",
  "discord_list_channel_invites",
  "discord_list_channels",
  "discord_list_forum_threads",
  "discord_list_guilds",
  "discord_list_invites",
  "discord_list_members",
  "discord_list_roles",
  "discord_list_scheduled_events",
  "discord_list_webhooks",
  "discord_lock_channel_permissions",
  "discord_move_channel",
  "discord_pin_message",
  "discord_prune_members",
  "discord_read_dms",
  "discord_read_messages",
  "discord_remove_reactions",
  "discord_remove_role",
  "discord_reply_dm",
  "discord_reply_message",
  "discord_reply_to_forum",
  "discord_reset_channel_permissions",
  "discord_search_guild_messages",
  "discord_search_members",
  "discord_search_messages",
  "discord_send_dm",
  "discord_send_dm_embed",
  "discord_send_embed",
  "discord_send_message",
  "discord_send_multiple_embeds",
  "discord_send_webhook_message",
  "discord_set_channel_position",
  "discord_set_forum_tags",
  "discord_set_member_permission",
  "discord_set_nickname",
  "discord_set_role_icon",
  "discord_set_role_permission",
  "discord_set_role_position",
  "discord_timeout_member",
  "discord_unban_member",
  "discord_update_forum_post",
  "discord_update_membership_screening",
])

const HYPARK_TOOLS = Object.freeze([
  "discord_delete_own_message",
  "discord_edit_own_message",
  "discord_get_bot",
  "discord_get_channel",
  "discord_get_guild",
  "discord_get_message",
  "discord_get_messages",
  "discord_list_channels",
  "discord_list_guilds",
  "discord_send_message",
])

const ORATORIAN_TOOLS = Object.freeze([
  "discord_add_reaction",
  "discord_add_role",
  "discord_ban_member",
  "discord_create_automod_rule",
  "discord_create_channel",
  "discord_create_emoji",
  "discord_create_event",
  "discord_create_invite",
  "discord_create_role",
  "discord_create_webhook",
  "discord_delete_automod_rule",
  "discord_delete_channel",
  "discord_delete_emoji",
  "discord_delete_event",
  "discord_delete_invite",
  "discord_delete_message",
  "discord_delete_role",
  "discord_delete_sticker",
  "discord_delete_webhook",
  "discord_edit_automod_rule",
  "discord_edit_channel",
  "discord_edit_guild",
  "discord_edit_message",
  "discord_edit_onboarding",
  "discord_edit_role",
  "discord_edit_webhook",
  "discord_edit_welcome_screen",
  "discord_get_audit_log",
  "discord_get_automod_rule",
  "discord_get_channel",
  "discord_get_channel_permissions",
  "discord_get_community_settings",
  "discord_get_guild",
  "discord_get_member",
  "discord_get_messages",
  "discord_get_onboarding",
  "discord_get_pinned_messages",
  "discord_get_welcome_screen",
  "discord_kick_member",
  "discord_leave_guild",
  "discord_list_automod_rules",
  "discord_list_bans",
  "discord_list_channels",
  "discord_list_emojis",
  "discord_list_events",
  "discord_list_guilds",
  "discord_list_invites",
  "discord_list_members",
  "discord_list_roles",
  "discord_list_stickers",
  "discord_list_webhooks",
  "discord_move_member",
  "discord_pin_message",
  "discord_prune_members",
  "discord_remove_channel_permissions",
  "discord_remove_reaction",
  "discord_remove_role",
  "discord_send_message",
  "discord_set_channel_permissions",
  "discord_set_nickname",
  "discord_set_role_positions",
  "discord_setup_community",
  "discord_setup_onboarding",
  "discord_sync_channel_permissions",
  "discord_timeout_member",
  "discord_unban_member",
  "discord_unpin_message",
])

const JAIMEN_BELL_TOOLS = Object.freeze([
  "create_channel",
  "create_message",
  "create_role",
  "delete_channel",
  "edit_channel",
  "edit_guild",
  "edit_role",
  "get_channel_permission_overwrites",
  "get_member_roles",
  "list_categories",
  "list_channels",
  "list_roles",
])

const TARGETED_READER_TOOLS = Object.freeze([
  "check_mentions",
  "fetch_messages",
  "get_thread",
  "post_message",
  "search_channel",
])

const TARGET_CHANNEL_LIFECYCLE = Object.freeze([
  "get_channel",
  "list_channels",
  "list_channel_permission_overwrites",
  "plan_channel_clone",
  "execute_channel_clone",
  "plan_channel_creation",
  "execute_channel_creation",
  "plan_channel_deletion",
  "execute_channel_deletion",
  "plan_channel_metadata_change",
  "execute_channel_metadata_change",
  "plan_channel_order",
  "execute_channel_order",
  "plan_channel_permission_overwrite",
  "execute_channel_permission_overwrite",
  "plan_channel_permission_sync",
  "execute_channel_permission_sync",
] as const satisfies readonly McpToolName[])

const TARGET_MESSAGE_LIFECYCLE = Object.freeze([
  "get_message",
  "list_message_pins",
  "list_message_replies",
  "read_messages",
  "recall_conversation",
  "search_messages",
  "send_message",
  "edit_own_message",
  "plan_message_deletion",
  "delete_messages",
  "plan_message_pin",
  "execute_message_pin",
  "plan_message_forward",
  "execute_message_forward",
  "plan_announcement_crosspost",
  "execute_announcement_crosspost",
  "plan_thread_creation",
  "execute_thread_creation",
  "plan_embed_message",
  "execute_embed_message",
] as const satisfies readonly McpToolName[])

const TARGET_MEMBER_LIFECYCLE = Object.freeze([
  "get_guild_member",
  "list_guild_members",
  "search_guild_members",
  "get_guild_ban",
  "list_guild_bans",
  "plan_member_moderation",
  "execute_member_moderation",
  "plan_bulk_guild_ban",
  "execute_bulk_guild_ban",
  "plan_member_role_change",
  "execute_member_role_change",
  "plan_bulk_member_role_change",
  "execute_bulk_member_role_change",
  "plan_member_nickname_change",
  "execute_member_nickname_change",
  "plan_guild_prune",
  "execute_guild_prune",
] as const satisfies readonly McpToolName[])

const CAPPYEO_GROUPS = Object.freeze([
  {
    disposition: "review-required",
    id: "application",
    instruction: "Re-select each application-owned asset or monetization outcome against the pinned current application; reviewed changes replace direct mutation.",
    outcome: "Application identity, Activity, assets, monetization, and bot profile",
    recipes: [],
    sourcePrefixes: ["app_emojis_", "application_", "entitlements_", "skus_", "subscriptions_"],
    targetTools: [
      "audit_application_entitlements",
      "audit_application_posture",
      "audit_application_role_connection_metadata",
      "audit_application_skus",
      "audit_application_subscriptions",
      "get_application_emoji",
      "get_application_entitlement",
      "get_current_bot_profile",
      "inspect_application_activity_instance",
      "list_application_emojis",
      "plan_application_emoji_change",
      "execute_application_emoji_change",
      "plan_application_role_connection_metadata_change",
      "execute_application_role_connection_metadata_change",
      "plan_bot_profile_change",
      "execute_bot_profile_change",
    ],
    trustChange: "Caller-selected application operations become pinned-current-application reads or reviewed changes with exact readback.",
  },
  {
    disposition: "supported",
    id: "audit-and-permissions",
    instruction: "Use exact-guild audit and permission explanation tools after activating explicit read scope.",
    outcome: "Audit-log and permission inspection",
    recipes: [],
    sourcePrefixes: ["audit_log_", "permissions_"],
    targetTools: ["audit_channel_role_access", "explain_channel_access", "explain_principal_permissions", "list_guild_audit_entries", "get_guild_audit_entry"],
    trustChange: "Results are bounded, identity-verified, and projected through the connector privacy boundary.",
  },
  {
    disposition: "review-required",
    id: "automod",
    instruction: "Audit exact rules first, then use the plan and execute pair for one acknowledged change.",
    outcome: "AutoMod inspection and changes",
    recipes: [],
    sourcePrefixes: ["automod_"],
    targetTools: ["get_automod_rule", "list_automod_rules", "plan_automod_change", "execute_automod_change", "verify_automod_change"],
    trustChange: "Immediate rule mutation becomes a fresh reviewed lifecycle with durable evidence and exact verification.",
  },
  {
    disposition: "review-required",
    id: "channels-and-threads",
    instruction: "Start with channel-reader scope, then enable only the exact channel or thread workflow needed through the config workbench.",
    outcome: "Channel, forum, thread, permission, and typing operations",
    recipes: [],
    sourcePrefixes: ["channels_", "threads_"],
    targetTools: [...TARGET_CHANNEL_LIFECYCLE, "list_active_threads", "list_archived_threads", "get_thread_membership", "get_thread_state", "plan_thread_change", "execute_thread_change", "plan_forum_post", "execute_forum_post", "signal_command_processing"],
    trustChange: "Raw mutations and free typing signals become exact-scope reviewed or command-bound operations.",
  },
  {
    disposition: "review-required",
    id: "application-commands",
    instruction: "Audit the pinned application's command inventories, then use the matching global or guild reviewed lifecycle.",
    outcome: "Application command inspection and replacement",
    recipes: [],
    sourcePrefixes: ["commands_"],
    targetTools: ["audit_application_commands", "plan_global_application_command_change", "execute_global_application_command_change", "plan_guild_application_command_change", "execute_guild_application_command_change"],
    trustChange: "Direct command CRUD becomes complete inventory review bound to the pinned application.",
  },
  {
    disposition: "review-required",
    id: "components",
    instruction: "Compile a typed bundled template when it fits or rebuild the bounded layout locally, inspect every link destination, configure each exact canonical HTTPS origin, then review, execute, and verify the exact message operation.",
    outcome: "Components v2 composition and delivery",
    recipes: ["channel-publisher"],
    sourcePrefixes: ["components_v2_"],
    targetTools: ["compile_component_template", "preview_component_layout", "plan_component_message", "execute_component_message", "verify_component_message"],
    trustChange: "A free-form or interpolated component send becomes typed local compilation or a schema-bounded callback-free preview, exact first-hop link-origin policy, and a reviewed one-shot lifecycle.",
  },
  {
    disposition: "review-required",
    id: "expressions-and-soundboard",
    instruction: "Inspect the exact guild asset first, then select the matching expression, application emoji, soundboard-change, or guarded playback workflow.",
    outcome: "Emoji, sticker, and soundboard operations",
    recipes: [],
    sourcePrefixes: ["emojis_", "soundboard_", "stickers_"],
    targetTools: ["get_guild_emoji", "get_guild_sticker", "list_default_soundboard_sounds", "list_guild_emojis", "list_guild_soundboard_sounds", "list_guild_stickers", "plan_guild_expression_change", "execute_guild_expression_change", "plan_guild_soundboard_change", "execute_guild_soundboard_change", "check_soundboard_playback", "play_soundboard_sound"],
    trustChange: "Asset writes and playback gain exact source and target scope, review, replay safety, and readback.",
  },
  {
    disposition: "review-required",
    id: "events-stage-and-voice",
    instruction: "Use the matching exact-guild read or reviewed scheduled-event, Stage, member-voice, or voice-status lifecycle.",
    outcome: "Scheduled events, Stage instances, voice state, and regions",
    recipes: [],
    sourcePrefixes: ["events_", "stage_instances_", "voice_"],
    targetTools: ["get_scheduled_event", "list_scheduled_events", "list_scheduled_event_users", "plan_scheduled_event_change", "execute_scheduled_event_change", "get_stage_instance", "list_stage_instances", "plan_stage_instance_change", "execute_stage_instance_change", "get_member_voice_state", "plan_member_voice_change", "execute_member_voice_change", "list_voice_regions"],
    trustChange: "Caller-directed state changes become exact-ID reviewed operations with permission and state evidence.",
  },
  {
    disposition: "review-required",
    id: "guild-lifecycle",
    instruction: "Choose the narrow audit or reviewed guild workflow; use guild-builder only when migrating a scaffold or blueprint outcome.",
    outcome: "Guild profile, community, onboarding, templates, roles, integrations, pruning, and blueprint operations",
    recipes: ["guild-builder"],
    sourcePrefixes: ["guild_", "onboarding_", "roles_", "templates_"],
    targetTools: ["get_guild_profile", "get_guild_vanity_url", "get_guild_welcome_screen", "get_guild_widget_settings", "list_guild_integrations", "list_guild_templates", "list_guild_voice_regions", "list_roles", "preview_guild_blueprint", "capture_guild_blueprint", "plan_guild_blueprint", "execute_guild_blueprint", "verify_guild_blueprint", "plan_guild_profile_change", "execute_guild_profile_change", "plan_guild_welcome_screen_change", "execute_guild_welcome_screen_change", "plan_guild_widget_settings_change", "execute_guild_widget_settings_change", "plan_guild_prune", "execute_guild_prune", "plan_guild_integration_deletion", "execute_guild_integration_deletion", "plan_role_creation", "execute_role_creation", "plan_role_configuration", "execute_role_configuration", "plan_role_deletion", "execute_role_deletion", "plan_role_order", "execute_role_order"],
    trustChange: "Broad direct guild mutation splits into narrow capabilities with fresh plans, durable coordination, and exact readback.",
  },
  {
    disposition: "intentionally-excluded",
    id: "embedded-intelligence",
    instruction: "Keep reasoning in the MCP host or chosen model provider and pass only the deliberate Discord operation to this connector.",
    outcome: "Embedded AI and third-party emoji search",
    recipes: [],
    sourcePrefixes: ["inspiration_", "intelligence_"],
    targetTools: [],
    trustChange: "The connector remains model-neutral and does not send Discord content to an implicit model or unrelated search provider.",
  },
  {
    disposition: "review-required",
    id: "interactions",
    instruction: "Use native Interaction ingress and one-shot continuations; never pass a reusable Discord interaction token through MCP input.",
    outcome: "Discord Interaction responses and follow-ups",
    recipes: [],
    sourcePrefixes: ["interactions_"],
    targetTools: ["list_pending_discord_interactions", "list_discord_interaction_continuations", "respond_to_discord_interaction", "send_discord_interaction_followup", "plan_native_interaction_command", "execute_native_interaction_command"],
    trustChange: "Reusable caller-supplied Interaction tokens become broker-private, bounded one-shot continuations.",
  },
  {
    disposition: "review-required",
    id: "invites",
    instruction: "Inspect redacted invite evidence or use the exact-channel reviewed creation and exact-invite deletion workflows.",
    outcome: "Invite inspection, creation, and deletion",
    recipes: [],
    sourcePrefixes: ["invites_"],
    targetTools: ["get_guild_invite", "list_guild_invites", "plan_invite_creation", "execute_invite_creation", "plan_invite_deletion", "execute_invite_deletion"],
    trustChange: "Reusable invite capabilities are redacted by default and mutations require exact scope and review.",
  },
  {
    disposition: "review-required",
    id: "members",
    instruction: "Enable only the exact member read, moderation, role, nickname, or bulk workflow required.",
    outcome: "Member inspection and administration",
    recipes: ["incident-response"],
    sourcePrefixes: ["members_"],
    targetTools: TARGET_MEMBER_LIFECYCLE,
    trustChange: "Immediate member mutations gain protected-user boundaries, complete hierarchy proof, review, and exact readback.",
  },
  {
    disposition: "review-required",
    id: "messages-reactions-and-polls",
    instruction: "Use channel-reader for reads, message-channel for plain sends or own-message edits, and channel-publisher only for broader reaction, component, or embed outcomes; destructive operations retain separate review.",
    outcome: "Message, reaction, thread, pin, crosspost, and poll operations",
    recipes: ["channel-publisher", "message-channel"],
    sourcePrefixes: ["messages_", "polls_", "reactions_"],
    targetTools: [...TARGET_MESSAGE_LIFECYCLE, "add_reaction", "add_reactions", "remove_own_reaction", "list_message_reactions", "list_reaction_users", "plan_reaction_moderation", "execute_reaction_moderation", "get_poll", "list_poll_answer_voters", "plan_poll_end", "execute_poll_end"],
    trustChange: "Message writes add explicit mention policy, anti-spam controls, replay safety, and content-free receipts.",
  },
  {
    disposition: "review-required",
    id: "orchestration",
    instruction: "Replace connector-owned pipelines with host-side progressive discovery, prompts, and explicit tool calls.",
    outcome: "Intent planning and connector-owned tool pipelines",
    recipes: [],
    sourceNames: ["discord_intent_plan", "mcp_pipeline"],
    targetTools: [],
    trustChange: "Planning remains visible to the MCP host instead of adding an opaque connector-side execution layer.",
  },
  {
    disposition: "review-required",
    id: "users-and-custody",
    instruction: "Use pinned bot-profile and installation audits, the direct-message recipe, or the reviewed departure workflow as appropriate.",
    outcome: "Current-user, guild inventory, direct-message creation, and guild departure",
    recipes: ["direct-messenger"],
    sourcePrefixes: ["users_"],
    targetTools: ["get_current_bot_profile", "audit_bot_installations", "plan_bot_profile_change", "execute_bot_profile_change", "plan_direct_message_change", "execute_direct_message_change", "plan_guild_departure", "execute_guild_departure"],
    trustChange: "Bot identity is pinned, DM authority is exact-user scoped, and guild departure becomes separately reviewed and recoverable.",
  },
  {
    disposition: "review-required",
    id: "webhooks",
    instruction: "Audit exact guild or channel webhooks, then choose a creation, change, deletion, or message workflow without exposing reusable credentials.",
    outcome: "Webhook inspection, administration, and message delivery",
    recipes: [],
    sourcePrefixes: ["webhooks_"],
    targetTools: ["audit_guild_webhooks", "get_channel_webhook", "get_webhook_message", "list_channel_webhooks", "plan_webhook_creation", "execute_webhook_creation", "plan_webhook_change", "execute_webhook_change", "plan_webhook_deletion", "execute_webhook_deletion", "send_webhook_message", "edit_webhook_message", "plan_webhook_message_deletion", "execute_webhook_message_deletion"],
    trustChange: "Webhook tokens remain connector-private capabilities and mutations gain target scope, one-shot coordination, and readback.",
  },
] as const satisfies readonly MigrationGroupDefinition[])

const PASYMPA_GROUPS = Object.freeze([
  {
    disposition: "supported",
    id: "server-inspection",
    instruction: "Use the read-only baseline to inspect exact guilds, channels, roles, members, permissions, and audit evidence.",
    outcome: "Guild, channel, role, member, permission, and audit inspection",
    recipes: [],
    sourceNames: ["discord_audit_permissions", "discord_find_channel_by_name", "discord_get_audit_log", "discord_get_channel_permissions", "discord_get_guild_info", "discord_get_member_info", "discord_get_role_members", "discord_get_server_stats", "discord_list_channels", "discord_list_guilds", "discord_list_members", "discord_list_roles", "discord_search_members"],
    targetTools: ["list_guilds", "get_guild_profile", "list_channels", "get_channel", "list_roles", "get_role", "list_guild_members", "get_guild_member", "search_guild_members", "list_channel_permission_overwrites", "explain_channel_access", "list_guild_audit_entries"],
    trustChange: "Reads are exact-scope, identity-bound, bounded, and privacy-projected.",
  },
  {
    disposition: "review-required",
    id: "channel-and-permission-administration",
    instruction: "Use the exact target channel lifecycle, with separate review for creation, deletion, movement, metadata, overwrite replacement, or parent sync.",
    outcome: "Channel creation, cloning, movement, deletion, and permission changes",
    recipes: [],
    sourceNames: ["discord_clone_channel", "discord_copy_permissions", "discord_create_channel", "discord_delete_channel", "discord_edit_channel", "discord_lock_channel_permissions", "discord_move_channel", "discord_reset_channel_permissions", "discord_set_channel_position", "discord_set_member_permission", "discord_set_role_permission"],
    targetTools: TARGET_CHANNEL_LIFECYCLE,
    trustChange: "Immediate structural writes become exact reviewed workflows with topology, authority, coordination, and readback evidence.",
  },
  {
    disposition: "review-required",
    id: "member-role-and-moderation",
    instruction: "Select the narrow role, nickname, moderation, bulk-ban, or prune workflow and configure its exact scope.",
    outcome: "Member roles, nicknames, moderation, bulk bans, and pruning",
    recipes: ["incident-response"],
    sourceNames: ["discord_add_role", "discord_ban_member", "discord_bulk_ban", "discord_kick_member", "discord_list_bans", "discord_prune_members", "discord_remove_role", "discord_set_nickname", "discord_timeout_member", "discord_unban_member"],
    targetTools: TARGET_MEMBER_LIFECYCLE,
    trustChange: "Protected-user, hierarchy, plan freshness, signed approval, and exact readback checks replace a shared write gate.",
  },
  {
    disposition: "review-required",
    id: "roles",
    instruction: "Inspect the role inventory, then use the separate creation, configuration, order, or deletion lifecycle.",
    outcome: "Role creation, editing, icon, ordering, and deletion",
    recipes: [],
    sourceNames: ["discord_create_role", "discord_delete_role", "discord_edit_role", "discord_set_role_icon", "discord_set_role_position"],
    targetTools: ["list_roles", "get_role", "plan_role_creation", "execute_role_creation", "plan_role_configuration", "execute_role_configuration", "plan_role_order", "execute_role_order", "plan_role_deletion", "execute_role_deletion"],
    trustChange: "Role writes are separated by risk and bound to complete hierarchy and exact readback evidence.",
  },
  {
    disposition: "review-required",
    id: "messages-and-reactions",
    instruction: "Use channel-reader for messages, search, and exact attachment retrieval; use message-channel for plain sends or own-message edits, and channel-publisher for broader reaction, component, or embed outcomes; keep deletion, pins, forwarding, crossposts, and threads on their reviewed routes.",
    outcome: "Messages, search, attachments, embeds, reactions, pins, forwarding, crossposts, and threads",
    recipes: ["channel-publisher", "message-channel"],
    sourceNames: ["discord_add_reaction", "discord_bulk_delete_messages", "discord_create_thread", "discord_crosspost_message", "discord_delete_message", "discord_edit_embed", "discord_edit_message", "discord_fetch_pinned_messages", "discord_forward_message", "discord_get_message_attachments", "discord_get_reactions", "discord_pin_message", "discord_read_messages", "discord_remove_reactions", "discord_reply_message", "discord_search_guild_messages", "discord_search_messages", "discord_send_embed", "discord_send_message", "discord_send_multiple_embeds"],
    targetTools: [...TARGET_MESSAGE_LIFECYCLE, "add_reaction", "add_reactions", "read_message_attachment", "list_message_reactions", "list_reaction_users", "plan_reaction_moderation", "execute_reaction_moderation"],
    trustChange: "Reads gain exact scope, pinned identity, privacy minimization, and transient attachment custody; writes add explicit mention handling, anti-spam controls, review where needed, and content-free receipts.",
  },
  {
    disposition: "review-required",
    id: "direct-messages",
    instruction: "Use the direct-messenger recipe and exact user allowlist, then review each send, edit, reply, or deletion outcome.",
    outcome: "Direct-message reads and writes",
    recipes: ["direct-messenger"],
    sourceNames: ["discord_delete_dm", "discord_edit_dm", "discord_edit_dm_embed", "discord_read_dms", "discord_reply_dm", "discord_send_dm", "discord_send_dm_embed"],
    targetTools: ["list_direct_messages", "get_direct_message", "plan_direct_message_change", "execute_direct_message_change", "verify_direct_message_change"],
    trustChange: "DM access becomes exact-user scoped and every mutation is reviewed and verified.",
  },
  {
    disposition: "review-required",
    id: "forums",
    instruction: "Inspect exact forum channels, posts, threads, and tags, then select the reviewed forum-post or tag workflow.",
    outcome: "Forum channels, posts, threads, replies, and tags",
    recipes: [],
    sourceNames: ["discord_create_forum_channel", "discord_create_forum_post", "discord_delete_forum_post", "discord_get_forum_channels", "discord_get_forum_post", "discord_get_forum_tags", "discord_list_forum_threads", "discord_reply_to_forum", "discord_set_forum_tags", "discord_update_forum_post"],
    targetTools: ["list_channels", "get_thread_state", "list_active_threads", "list_archived_threads", "audit_forum_tags", "plan_forum_post", "execute_forum_post", "plan_forum_tag_change", "execute_forum_tag_change"],
    trustChange: "Forum writes become exact-channel reviewed operations with tag and thread state readback.",
  },
  {
    disposition: "review-required",
    id: "scheduled-events",
    instruction: "Use exact event reads and the reviewed create, edit, or delete lifecycle; create invite links separately.",
    outcome: "Scheduled events, subscribers, and event invites",
    recipes: [],
    sourceNames: ["discord_create_event_invite", "discord_create_scheduled_event", "discord_delete_scheduled_event", "discord_edit_scheduled_event", "discord_get_event_subscribers", "discord_get_scheduled_event", "discord_list_scheduled_events"],
    targetTools: ["get_scheduled_event", "list_scheduled_events", "list_scheduled_event_users", "plan_scheduled_event_change", "execute_scheduled_event_change", "plan_invite_creation", "execute_invite_creation"],
    trustChange: "Event changes and invite capabilities become separate exact-scope reviewed outcomes.",
  },
  {
    disposition: "review-required",
    id: "invites-and-announcements",
    instruction: "Use redacted invite inspection and reviewed create or delete workflows; follow announcement channels through the reviewed subscription lifecycle.",
    outcome: "Invites and announcement following",
    recipes: [],
    sourceNames: ["discord_create_invite", "discord_delete_invite", "discord_follow_announcement_channel", "discord_get_invite", "discord_list_channel_invites", "discord_list_invites"],
    targetTools: ["get_guild_invite", "list_guild_invites", "plan_invite_creation", "execute_invite_creation", "plan_invite_deletion", "execute_invite_deletion", "list_announcement_subscriptions", "plan_announcement_subscription", "execute_announcement_subscription"],
    trustChange: "Invite codes are redacted and announcement subscriptions gain exact source and destination review.",
  },
  {
    disposition: "review-required",
    id: "webhooks",
    instruction: "Audit exact webhook inventory before selecting creation, change, deletion, or message operations.",
    outcome: "Webhook inspection, administration, and messages",
    recipes: [],
    sourceNames: ["discord_create_webhook", "discord_delete_webhook", "discord_delete_webhook_message", "discord_edit_webhook", "discord_edit_webhook_message", "discord_fetch_webhook_message", "discord_list_webhooks", "discord_send_webhook_message"],
    targetTools: ["audit_guild_webhooks", "get_channel_webhook", "get_webhook_message", "list_channel_webhooks", "plan_webhook_creation", "execute_webhook_creation", "plan_webhook_change", "execute_webhook_change", "plan_webhook_deletion", "execute_webhook_deletion", "send_webhook_message", "edit_webhook_message", "plan_webhook_message_deletion", "execute_webhook_message_deletion"],
    trustChange: "Reusable webhook credentials remain private and mutations gain exact scope, coordination, and readback.",
  },
  {
    disposition: "review-required",
    id: "membership-screening",
    instruction: "Inspect onboarding state and use the reviewed member-verification or onboarding workflow for the intended change.",
    outcome: "Membership screening inspection and changes",
    recipes: [],
    sourceNames: ["discord_get_membership_screening", "discord_update_membership_screening"],
    targetTools: ["get_guild_onboarding", "plan_member_verification_change", "execute_member_verification_change", "plan_onboarding_change", "execute_onboarding_change"],
    trustChange: "Screening changes become exact-guild reviewed operations with complete state evidence.",
  },
] as const satisfies readonly MigrationGroupDefinition[])

const HYPARK_GROUPS = Object.freeze([
  {
    disposition: "supported",
    id: "identity-and-guild-reads",
    instruction: "Create a read-only exact-scope policy and use the corresponding bounded identity, guild, and channel reads.",
    outcome: "Bot, guild, and channel inspection",
    recipes: [],
    sourceNames: ["discord_get_bot", "discord_get_channel", "discord_get_guild", "discord_list_channels", "discord_list_guilds"],
    targetTools: ["get_current_bot_profile", "get_channel", "get_guild_profile", "list_channels", "list_guilds"],
    trustChange: "The bot is pinned to expected application and bot IDs, with separate exact read scope.",
  },
  {
    disposition: "supported",
    id: "message-reads",
    instruction: "Use the channel-reader preset and bounded exact-channel message reads.",
    outcome: "Message list and exact-message reads",
    recipes: [],
    sourceNames: ["discord_get_message", "discord_get_messages"],
    targetTools: ["get_message", "read_messages"],
    trustChange: "Message results retain exact scope and a stricter minimized projection with no connector persistence.",
  },
  {
    disposition: "review-required",
    id: "own-message-writes",
    instruction: "Add message-channel only for exact target channels; keep sends and own-message edits replay-safe and use reviewed deletion.",
    outcome: "Send, edit-own, and delete-own message operations",
    recipes: ["message-channel"],
    sourceNames: ["discord_delete_own_message", "discord_edit_own_message", "discord_send_message"],
    targetTools: ["send_message", "edit_own_message", "plan_message_deletion", "delete_messages"],
    trustChange: "The existing nonce and mention safeguards gain explicit plan review where destructive, durable coordination, and content-free receipts.",
  },
] as const satisfies readonly MigrationGroupDefinition[])

const JAIMEN_BELL_GROUPS = Object.freeze([
  {
    disposition: "supported",
    id: "guild-structure-reads",
    instruction: "Use server-observer to inspect exact channel, role, overwrite, and member-role evidence.",
    outcome: "Channel, category, role, permission, and member-role inspection",
    recipes: [],
    sourceNames: ["get_channel_permission_overwrites", "get_member_roles", "list_categories", "list_channels", "list_roles"],
    targetTools: ["list_channels", "list_roles", "list_channel_permission_overwrites", "get_guild_member"],
    trustChange: "Reads become pinned-identity, exact-guild operations with bounded privacy projections.",
  },
  {
    disposition: "review-required",
    id: "channel-and-role-administration",
    instruction: "Replace the shared write switch with the exact channel or role lifecycle and explicit policy scope.",
    outcome: "Channel and role creation, editing, and channel deletion",
    recipes: [],
    sourceNames: ["create_channel", "create_role", "delete_channel", "edit_channel", "edit_role"],
    targetTools: [...TARGET_CHANNEL_LIFECYCLE, "plan_role_creation", "execute_role_creation", "plan_role_configuration", "execute_role_configuration"],
    trustChange: "A global write gate becomes capability-specific scope, fresh review, durable coordination, and exact readback.",
  },
  {
    disposition: "review-required",
    id: "guild-profile",
    instruction: "Use the reviewed exact-guild profile lifecycle and its bounded local asset inputs.",
    outcome: "Guild profile editing",
    recipes: [],
    sourceNames: ["edit_guild"],
    targetTools: ["get_guild_profile", "plan_guild_profile_change", "execute_guild_profile_change"],
    trustChange: "Free-form guild patching becomes a typed, identity-bound, reviewed change with exact readback.",
  },
  {
    disposition: "review-required",
    id: "message-publishing",
    instruction: "Add message-channel only for exact target channels and use replay-safe sends with explicit mention policy.",
    outcome: "Message posting",
    recipes: ["message-channel"],
    sourceNames: ["create_message"],
    targetTools: ["send_message"],
    trustChange: "A global write gate becomes exact-channel scope, anti-spam controls, nonce replay safety, and content-free receipts.",
  },
] as const satisfies readonly MigrationGroupDefinition[])

const ORATORIAN_GROUPS = Object.freeze([
  {
    disposition: "supported",
    id: "guild-and-channel-reads",
    instruction: "Use exact-scope read tools for guild, channel, member, role, permission, audit, and pinned-message inspection.",
    outcome: "Guild, channel, member, role, permission, audit, and pin reads",
    recipes: [],
    sourceNames: ["discord_get_audit_log", "discord_get_channel", "discord_get_channel_permissions", "discord_get_guild", "discord_get_member", "discord_get_messages", "discord_get_pinned_messages", "discord_list_bans", "discord_list_channels", "discord_list_guilds", "discord_list_members", "discord_list_roles"],
    targetTools: ["get_channel", "get_guild_profile", "get_guild_member", "list_channels", "list_guilds", "list_guild_members", "list_roles", "read_messages", "list_message_pins", "list_channel_permission_overwrites", "list_guild_audit_entries", "list_guild_bans"],
    trustChange: "Reads become pinned-identity, bounded, and privacy-projected within exact local scope.",
  },
  {
    disposition: "review-required",
    id: "channels-and-permissions",
    instruction: "Select the exact channel structural, overwrite, or parent-sync lifecycle instead of direct modification.",
    outcome: "Channel creation, edits, deletion, and permission synchronization",
    recipes: [],
    sourceNames: ["discord_create_channel", "discord_delete_channel", "discord_edit_channel", "discord_remove_channel_permissions", "discord_set_channel_permissions", "discord_sync_channel_permissions"],
    targetTools: TARGET_CHANNEL_LIFECYCLE,
    trustChange: "Direct channel writes gain topology, capacity, hierarchy, plan freshness, one-shot coordination, and exact readback.",
  },
  {
    disposition: "review-required",
    id: "messages-and-reactions",
    instruction: "Use message-channel for plain sends or own-message edits and channel-publisher for reaction or component outcomes; retain reviewed routes for message deletion and pins.",
    outcome: "Messages, reactions, and pins",
    recipes: ["channel-publisher", "message-channel"],
    sourceNames: ["discord_add_reaction", "discord_delete_message", "discord_edit_message", "discord_pin_message", "discord_remove_reaction", "discord_send_message", "discord_unpin_message"],
    targetTools: ["send_message", "edit_own_message", "add_reaction", "add_reactions", "remove_own_reaction", "plan_reaction_moderation", "execute_reaction_moderation", "plan_message_deletion", "delete_messages", "plan_message_pin", "execute_message_pin"],
    trustChange: "Message writes become exact-channel, mention-safe, replay-safe, and reviewed when high-impact.",
  },
  {
    disposition: "review-required",
    id: "member-and-role-administration",
    instruction: "Use separate role, nickname, member-voice, moderation, prune, and ordering workflows with exact scope.",
    outcome: "Member moderation, movement, nickname, roles, and pruning",
    recipes: ["incident-response"],
    sourceNames: ["discord_add_role", "discord_ban_member", "discord_create_role", "discord_delete_role", "discord_edit_role", "discord_kick_member", "discord_move_member", "discord_prune_members", "discord_remove_role", "discord_set_nickname", "discord_set_role_positions", "discord_timeout_member", "discord_unban_member"],
    targetTools: [...TARGET_MEMBER_LIFECYCLE, "plan_member_voice_change", "execute_member_voice_change", "plan_role_creation", "execute_role_creation", "plan_role_configuration", "execute_role_configuration", "plan_role_deletion", "execute_role_deletion", "plan_role_order", "execute_role_order"],
    trustChange: "Immediate member and role writes gain protected-user, hierarchy, freshness, coordination, and readback controls.",
  },
  {
    disposition: "review-required",
    id: "automod",
    instruction: "Audit exact AutoMod rules, then plan, execute, and verify one bounded change.",
    outcome: "AutoMod inspection and changes",
    recipes: [],
    sourceNames: ["discord_create_automod_rule", "discord_delete_automod_rule", "discord_edit_automod_rule", "discord_get_automod_rule", "discord_list_automod_rules"],
    targetTools: ["get_automod_rule", "list_automod_rules", "plan_automod_change", "execute_automod_change", "verify_automod_change"],
    trustChange: "Direct rule mutation becomes a fresh reviewed lifecycle with durable evidence and exact verification.",
  },
  {
    disposition: "review-required",
    id: "guild-community-and-departure",
    instruction: "Use the matching reviewed profile, welcome-screen, onboarding, community, or departure lifecycle.",
    outcome: "Guild profile, community, onboarding, welcome screen, and departure",
    recipes: [],
    sourceNames: ["discord_edit_guild", "discord_edit_onboarding", "discord_edit_welcome_screen", "discord_get_community_settings", "discord_get_onboarding", "discord_get_welcome_screen", "discord_leave_guild", "discord_setup_community", "discord_setup_onboarding"],
    targetTools: ["get_guild_profile", "get_guild_onboarding", "get_guild_welcome_screen", "audit_guild_community", "plan_guild_profile_change", "execute_guild_profile_change", "plan_onboarding_change", "execute_onboarding_change", "plan_guild_welcome_screen_change", "execute_guild_welcome_screen_change", "plan_guild_community_change", "execute_guild_community_change", "plan_guild_departure", "execute_guild_departure"],
    trustChange: "Broad direct guild changes split into target-specific reviewed lifecycles, and departure gains absence proof and ambiguity quarantine.",
  },
  {
    disposition: "review-required",
    id: "events-invites-webhooks-and-assets",
    instruction: "Inspect the exact inventory first, then choose the narrow reviewed event, invite, webhook, emoji, or sticker operation.",
    outcome: "Events, invites, webhooks, emojis, and stickers",
    recipes: [],
    sourceNames: ["discord_create_emoji", "discord_create_event", "discord_create_invite", "discord_create_webhook", "discord_delete_emoji", "discord_delete_event", "discord_delete_invite", "discord_delete_sticker", "discord_delete_webhook", "discord_edit_webhook", "discord_list_emojis", "discord_list_events", "discord_list_invites", "discord_list_stickers", "discord_list_webhooks"],
    targetTools: ["list_guild_emojis", "list_guild_stickers", "list_scheduled_events", "list_guild_invites", "audit_guild_webhooks", "plan_guild_expression_change", "execute_guild_expression_change", "plan_scheduled_event_change", "execute_scheduled_event_change", "plan_invite_creation", "execute_invite_creation", "plan_invite_deletion", "execute_invite_deletion", "plan_webhook_creation", "execute_webhook_creation", "plan_webhook_change", "execute_webhook_change", "plan_webhook_deletion", "execute_webhook_deletion"],
    trustChange: "Collection writes become separately scoped, reviewed, non-retried operations with exact inventory readback.",
  },
] as const satisfies readonly MigrationGroupDefinition[])

const TARGETED_READER_GROUPS = Object.freeze([
  {
    disposition: "supported",
    id: "message-and-thread-reads",
    instruction: "Use channel-reader and exact channel or thread IDs for bounded reads and indexed search.",
    outcome: "Recent messages, channel search, and thread reads",
    recipes: [],
    sourceNames: ["fetch_messages", "get_thread", "search_channel"],
    targetTools: ["read_messages", "search_messages", "get_thread_state"],
    trustChange: "Reads gain exact local scope, pinned identity, strict bounds, untrusted-text marking, and no connector persistence.",
  },
  {
    disposition: "review-required",
    id: "mention-check",
    instruction: "Replace partial username matching with an exact user ID and bounded message search inside allowed channel scope.",
    outcome: "Mention inspection",
    recipes: [],
    sourceNames: ["check_mentions"],
    targetTools: ["search_messages", "read_messages"],
    trustChange: "Presentation-name matching is removed in favor of exact Discord identity and scoped evidence.",
  },
  {
    disposition: "review-required",
    id: "message-publishing",
    instruction: "Add message-channel for exact destination channels and express mentions through the explicit mention policy.",
    outcome: "Message posting with optional mention",
    recipes: ["message-channel"],
    sourceNames: ["post_message"],
    targetTools: ["send_message"],
    trustChange: "Free-form posting gains exact channel scope, explicit allowed mentions, anti-spam controls, nonce replay safety, and content-free receipts.",
  },
] as const satisfies readonly MigrationGroupDefinition[])

export const MIGRATION_SOURCE_DEFINITIONS = Object.freeze([
  {
    auditFidelity: "tagged-source",
    auditedInventoryDigest: "sha256:dab2107a16da8e9738281c2db287a13dadfff5d82abe8e796cd7bd8b9f166a92",
    baselinePreset: "channel-reader",
    evidenceUrl: "https://github.com/cappyeo/discord-mcp/tree/0bdf017fb33a6da17a9eed1b7d98f1952f300777",
    groups: CAPPYEO_GROUPS,
    id: "cappyeo@0.26.0",
    limitations: ["The source release exposes optional HTTP, Gateway, embedded intelligence, and third-party integration modes that are not configuration-compatible with this local stdio connector."],
    product: "Cappyeo",
    registryName: "io.github.cappyeo/discord-mcp",
    registryUrl: "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.cappyeo%2Fdiscord-mcp/versions/0.26.0",
    sourceTools: CAPPYEO_TOOLS,
    version: "0.26.0",
  },
  {
    auditFidelity: "tagged-source",
    auditedInventoryDigest: "sha256:00c78aca6e28791583b97758cf71d0417133653b45136e1362c866a1741fbca7",
    baselinePreset: "channel-reader",
    evidenceUrl: "https://github.com/hypark5540/discord-mcp/tree/4f7672b0a02f97f7f260eef128f8bf6747574826",
    groups: HYPARK_GROUPS,
    id: "hypark@0.1.1",
    limitations: ["The source release's optional writes are represented as migration outcomes only; its environment-policy shape is not imported."],
    product: "Hypark",
    registryName: "io.github.hypark5540/discord-mcp",
    registryUrl: "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.hypark5540%2Fdiscord-mcp/versions/0.1.1",
    sourceTools: HYPARK_TOOLS,
    version: "0.1.1",
  },
  {
    auditFidelity: "version-matched-public-source",
    auditedInventoryDigest: "sha256:4d734a2df79ad658071f5d89c5fb2f9f344195ebef08dda9fbfcad194394cef4",
    baselinePreset: "server-observer",
    evidenceUrl: "https://github.com/jaimenbell/discord-mcp/tree/3fb0bec658a00c198d1112e2e3eabebbc6990284",
    groups: JAIMEN_BELL_GROUPS,
    id: "jaimen-bell@0.1.1",
    limitations: ["The exact PyPI release and matching commit-pinned public source were audited, but the project did not publish a source tag for this version."],
    product: "Jaimen Bell",
    registryName: "io.github.jaimenbell/discord-mcp",
    registryUrl: "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.jaimenbell%2Fdiscord-mcp/versions/0.1.1",
    sourceTools: JAIMEN_BELL_TOOLS,
    version: "0.1.1",
  },
  {
    auditFidelity: "tagged-source",
    auditedInventoryDigest: "sha256:731c19148881157e5a193234ee1d5c4a986dc56f407286d718b9af94a684f628",
    baselinePreset: "channel-reader",
    evidenceUrl: "https://github.com/Oratorian/discord-node-mcp/tree/fbea69d69751858a5e6813022b5f6424a80a2292",
    groups: ORATORIAN_GROUPS,
    id: "oratorian@1.1.4",
    limitations: ["The source release supports both stdio and HTTP; this plan targets migration into local stdio custody and does not recreate remote exposure."],
    product: "Oratorian",
    registryName: "io.github.Oratorian/discord-node-mcp",
    registryUrl: "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.Oratorian%2Fdiscord-node-mcp/versions/1.1.4",
    sourceTools: ORATORIAN_TOOLS,
    version: "1.1.4",
  },
  {
    auditFidelity: "tagged-source",
    auditedInventoryDigest: "sha256:d42e8d5df89d88e57ad94b73a5c978573ebb8865bf2de453c409be23a9d6c259",
    baselinePreset: "channel-reader",
    evidenceUrl: "https://github.com/PaSympa/discord-mcp/tree/5d13fea701d567f1c67a4f21f75844db1f1acda4",
    groups: PASYMPA_GROUPS,
    id: "pasympa@2.2.0",
    limitations: ["The source release's broad environment-configured write surface is translated into separate exact-scope target workflows, not imported as one authority switch."],
    product: "PaSympa",
    registryName: "io.github.PaSympa/discord-mcp",
    registryUrl: "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.PaSympa%2Fdiscord-mcp/versions/2.2.0",
    sourceTools: PASYMPA_TOOLS,
    version: "2.2.0",
  },
  {
    auditFidelity: "version-matched-public-source",
    auditedInventoryDigest: "sha256:62ea5e6008bd9160fbbeeab8985ca64ad2b33a3912015008b817b0ad83ce34c1",
    baselinePreset: "channel-reader",
    evidenceUrl: "https://github.com/Targeted-Design-Agency/mcp-discord-reader/tree/9e755ba875c04b952b82643dd4c52a7285adc3f1",
    groups: TARGETED_READER_GROUPS,
    id: "targeted-reader@1.0.0",
    limitations: ["The Registry version matches commit-pinned public source without a source tag or installable package declaration; the plan preserves that weaker audit fidelity."],
    product: "Targeted Reader",
    registryName: "io.github.targeteddesignagency-blip/discord-reader",
    registryUrl: "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.targeteddesignagency-blip%2Fdiscord-reader/versions/1.0.0",
    sourceTools: TARGETED_READER_TOOLS,
    version: "1.0.0",
  },
] as const satisfies readonly MigrationSourceDefinition[])
